### ISSUE TITLE
Guillemets (« ») have the same glyph as single guillemets (‹ ›)

### ISSUE THREAD

**Issue by fitojb** [googlefonts/pangolin#1]
![captura de pantalla de 2017-03-15 01-26-24](https://cloud.githubusercontent.com/assets/554953/23937700/7b5d55e4-091e-11e7-92f5-dfb51a50bdc8.png)

**Comment by m4rc1e** [comment]
Apologies, I didn't mean to close this.

Latest commit solves this.

![pangoln-guillemot](https://cloud.githubusercontent.com/assets/7525512/23940939/ba5e5cc6-095e-11e7-9d1a-7616bcf38a1f.gif)

**Comment by m4rc1e** [comment]
Closing this and making a pr to google/fonts

**Comment by davelab6** [comment]
@fitojb love it! 

@m4rc1e i wonder if we could catch this with a Glyphs source checking script that counts the number of contours is within an expected range and warns (not errors) when out of bounds; eg guilemets should have 2 contours each :)

**Comment by m4rc1e** [comment]
@davelab6  @graphicore added a test to check if two components are duplicated on top of one another. This can find these errors. I'm also tempted to add another to check if the component counts are correct for certain glyphs.
